name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'build/*'
          target: '/var/www/html'

      - name: SSH into EC2 and restart server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl restart apache2




# name: Deploy to EC2

# on:
#   push:
#     branches:
#       - main  # Change this to your main branch

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Setup Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '14'  # Change this to your Node.js version

#       - name: Install dependencies
#         run: npm install  # Change this to your build script if needed

#       - name: Build
#         run: npm run build  # Change this to your build script if needed

#       - name: Deploy to EC2
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ EC2_USERNAME }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           source: 'build/*'
#           target: '/var/www/html'

#           script: |
#             sudo yum update -y
#             sudo yum install -y git
#             curl -fsSL https://rpm.nodesource.com/setup_16.x | sudo -E bash -
#             sudo yum install -y nodejs
